[platformio]
src_dir = .

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
lib_deps =
    symlink://../..
    https://github.com/packerlschupfer/ESP32-Logger.git

[env:core2_espressif32]
extends = env:esp32dev
platform = espressif32
